version: "3"

services:
  vote:
    image: spara/vote:latest
    # command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: spara/worker:latest

  db:
    image: postgres:9.4

  result:
    image: spara/result:latest
    # command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
